services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - AUTHENTICATION_API_KEY=sua-chave-super-secreta-aqui-123456
      - DATABASE_PROVIDER=
      - LOG_LEVEL=ERROR
      - QRCODE_LIMIT=30
    volumes:
      - evolution_data:/evolution/instances
    restart: unless-stopped

volumes:
  evolution_data:
