version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: sp-postgres
    environment:
      POSTGRES_DB: sp_database
      POSTGRES_USER: sp_user
      POSTGRES_PASSWORD: sp_password123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sp_user -d sp_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Evolution API (WhatsApp)
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: sp-evolution-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - AUTHENTICATION_API_KEY=sp-evolution-key-2025
      - DATABASE_ENABLED=false
      - DATABASE_PROVIDER=
      - LOG_LEVEL=ERROR
      - QRCODE_LIMIT=30
    volumes:
      - evolution_data:/evolution/instances
    networks:
      - sp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # SP.Api (.NET Application)
  sp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sp-api
    ports:
      - "7169:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=sp_database;Username=sp_user;Password=sp_password123;
      - WhatsApp__Terceiros__ApiUrl=http://evolution-api:8080
      - WhatsApp__Terceiros__ApiKey=sp-evolution-key-2025
    depends_on:
      postgres:
        condition: service_healthy
      evolution-api:
        condition: service_started
    networks:
      - sp_network
    restart: unless-stopped

  # pgAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sp-pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sp.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sp_network

volumes:
  postgres_data:
    driver: local
  evolution_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  sp_network:
    driver: bridge
