// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SP.Infraestrutura.Data.Context;

#nullable disable

namespace SP.Infraestrutura.Migrations
{
    [DbContext(typeof(SPContext))]
    [Migration("20251003205552_AddLocalizacaoEntities")]
    partial class AddLocalizacaoEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SP.Dominio.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceiteLgpd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("character(14)")
                        .IsFixedLength();

                    b.Property<int?>("CidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("CidadeNome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContatoEmergencia")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<string>("FormaPagamentoPreferida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StatusFinanceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefoneEmergencia")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ValorSessao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_clientes_ativo");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_cpf");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_clientes_cidade_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_email");

                    b.HasIndex("StatusFinanceiro")
                        .HasDatabaseName("ix_clientes_status_financeiro");

                    b.HasIndex("Nome", "Ativo")
                        .HasDatabaseName("ix_clientes_nome_ativo");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("SP.Dominio.Localizacao.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Area")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("CodigoIBGE")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(7)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(11,8)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int?>("Populacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_cidades_ativo");

                    b.HasIndex("CEP")
                        .HasDatabaseName("ix_cidades_cep");

                    b.HasIndex("CodigoIBGE")
                        .IsUnique()
                        .HasDatabaseName("ix_cidades_codigo_ibge")
                        .HasFilter("\"CodigoIBGE\" IS NOT NULL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_cidades_nome");

                    b.HasIndex("EstadoId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_cidades_estado_nome");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_cidades_coordenadas")
                        .HasFilter("\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL");

                    b.ToTable("Cidades", (string)null);
                });

            modelBuilder.Entity("SP.Dominio.Localizacao.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoIBGE")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(2)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.Property<string>("Regiao")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_estados_ativo");

                    b.HasIndex("CodigoIBGE")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_codigo_ibge")
                        .HasFilter("\"CodigoIBGE\" IS NOT NULL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_estados_nome");

                    b.HasIndex("Regiao")
                        .HasDatabaseName("ix_estados_regiao");

                    b.HasIndex("PaisId", "Sigla")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_pais_sigla");

                    b.ToTable("Estados", (string)null);
                });

            modelBuilder.Entity("SP.Dominio.Localizacao.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(2)");

                    b.Property<string>("CodigoISO3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(3)");

                    b.Property<string>("CodigoTelefone")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(5)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_paises_ativo");

                    b.HasIndex("CodigoISO")
                        .IsUnique()
                        .HasDatabaseName("ix_paises_codigo_iso");

                    b.HasIndex("CodigoISO3")
                        .IsUnique()
                        .HasDatabaseName("ix_paises_codigo_iso3");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_paises_nome");

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("SP.Dominio.Sessoes.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnotacoesClinicas")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConsiderarFaturamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataHoraAgendada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataHoraRealizada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DuracaoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<int?>("DuracaoRealMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Periodicidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int?>("SessaoOriginalId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_sessoes_ativo");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_sessoes_cliente_id");

                    b.HasIndex("DataHoraAgendada")
                        .HasDatabaseName("ix_sessoes_data_hora_agendada");

                    b.HasIndex("Pago")
                        .HasDatabaseName("ix_sessoes_pago");

                    b.HasIndex("SessaoOriginalId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sessoes_status");

                    b.HasIndex("ClienteId", "DataHoraAgendada")
                        .IsUnique()
                        .HasDatabaseName("ix_sessoes_cliente_data");

                    b.ToTable("Sessoes", (string)null);
                });

            modelBuilder.Entity("SP.Dominio.Clientes.Cliente", b =>
                {
                    b.HasOne("SP.Dominio.Localizacao.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("SP.Dominio.Localizacao.Cidade", b =>
                {
                    b.HasOne("SP.Dominio.Localizacao.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SP.Dominio.Localizacao.Estado", b =>
                {
                    b.HasOne("SP.Dominio.Localizacao.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("SP.Dominio.Sessoes.Sessao", b =>
                {
                    b.HasOne("SP.Dominio.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SP.Dominio.Sessoes.Sessao", "SessaoOriginal")
                        .WithMany("SessoesReagendadas")
                        .HasForeignKey("SessaoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("SessaoOriginal");
                });

            modelBuilder.Entity("SP.Dominio.Localizacao.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("SP.Dominio.Localizacao.Pais", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("SP.Dominio.Sessoes.Sessao", b =>
                {
                    b.Navigation("SessoesReagendadas");
                });
#pragma warning restore 612, 618
        }
    }
}
